### ISSUE TITLE
Whitespace sensitivity

### ISSUE THREAD

**Issue by MrDOS** [SamBoyd/coderacer-issues#1]
Coderacer seems to autoindent on newline to match the indentation of the sample. That's good! But the editor doesn't trim trailing whitespace on newline, or undo automatic indenting on blank lines. Both of these mean that manual intervention is required before blank lines will be accepted. I haven't tried to figure out whether this negatively impacts accuracy.

For example, I was just given this sample to copy:

```java
package com.iluwatar.command;


public abstract class Command {

  public abstract void execute(Target target);

  public abstract void undo();

  public abstract void redo();

  @Override
  public abstract String toString();
}
```

By the time I'd finished typing the sample, my input buffer contained (spaces replaced with `␣`):

```java
package com.iluwatar.command;


public abstract class Command {
␣␣
␣␣public abstract void execute(Target target);
␣␣
␣␣public abstract void undo();
␣␣
␣␣public abstract void redo();
␣␣
␣␣@Override
␣␣public abstract String toString();
}
```

In order for the submission to be accepted, I had to navigate back through my entry (arrow keys) and remove the whitespace. The editor should either disregard leading/trailing whitespace when comparing the sample to the input, or should remove autoindent whitespace from lines not modified by the user (i.e., lines consisting _only_ of autoindent whitespace).

**Comment by SamBoyd** [comment]
This has been fixed with the introduction of AST parsing of the typed text
