### ISSUE TITLE
First newline after a brace is ignored

### ISSUE THREAD

**Issue by MrDOS** [SamBoyd/coderacer-issues#2]
Firefox 77.0.1. I need to hit Enter twice before the input editor acknowledges my first newline. Subsequent newlines are accepted correctly. The first newline seems to be eaten entirely; it doesn't provoke an invisible character/zero-width space or anything.

**Comment by MrDOS** [comment]
Having done a few more races, I have a clearer idea of the issue now: it's not the first newline, it's the first newline after a brace character. I think.

**Comment by SamBoyd** [comment]
This is fixed - The typed text is now parsed to an AST and checked so that formatting characters can be ignored

**Comment by MrDOS** [comment]
It is _so_ much easier to race now that this is in place. Thank you!
