### ISSUE TITLE
Speed bumps

### ISSUE THREAD

**Issue by MrDOS** [SamBoyd/coderacer-issues#3]
The [pre-race page](https://app.coderacer.dev/) currently shows this high score table:

> ### High Scores
> | Username | Template | CPM | Accuracy | Time | Length |
> | -------- | -------- | --- | -------- | ---- | ------ |
> | Guest_1281 | java_design_patterns_13 | 196 | 96 | 1min10sec | 221 |
> | Guest_4609 | howdoi_4 | 246 | 66 | 44sec | 121 |
> | Guest_1774 | java_design_patterns_13 | 198 | 75 | 1min28sec | 221 |
> | Guest_1281 | howdoi_4 | 159 | 76 | 1min0sec | 121 |
> | BillyBones | howdoi_6 | 502 | 101 | 16sec | 136 |
> | Guest_398 | flask_2 | 505 | 95 | 14sec | 113 |
> | Guest_4208 | mockito_3 | 460 | 101 | 15sec | 117 |
> | Guest_398 | flask_4 | 475 | 92 | 28sec | 206 |
> | BillyBones | flask_2 | 427 | 99 | 16sec | 113 |

400-500 CPM is _fast_! Have you considered doing anything to verify the humanity/capability of the users submitting these results? A CAPTCHA typing test (ala TypeRacer), burst limiting to prevent copy/paste or macro insertion, etc. Or maybe you have one, and I just haven't hit it yet :)

**Comment by SamBoyd** [comment]
I have added an extra post race speed test which quick users will have to complete to qualify their speed

**Comment by MrDOS** [comment]
Got around to trying another race, and hit this test. Nice!
